import { createHash } from "node:crypto";
import type { EmitContext, Model, ModelProperty, Program, Scalar } from "@typespec/compiler";
import { emitFile, navigateProgram, resolveEncodedName } from "@typespec/compiler";
import {
  getColumnName,
  getColumnTypeOverride,
  getIndexes,
  getTableName,
  hasRowTimestamp,
  isPrimaryKey,
} from "./decorators.js";
import { mapType } from "./type-map.js";

const HEADER = [
  "// <auto-generated/>",
  "// Copyright (c) 2025-2026 ancplua",
  "// Source: **/*.tsp via @ancplua/typespec-emit-duckdb",
  "#nullable enable",
  "",
].join("\n");

interface Column { name: string; type: string; notNull: boolean; primaryKey: boolean; indexes: string[]; }
interface Table { name: string; model: Model; columns: Column[]; }

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  // Dedupe by table name: TypeSpec visibility transforms (Create<T>, MergePatchUpdate<T>, …)
  // produce mutated model instances that inherit the `@@duckdbTable` augment from the source
  // entity. Without dedupe, every Create<T> / MergePatchUpdate<T> reference in routes.tsp
  // would emit a competing DDL constant with the visibility-filtered subset of columns.
  // The canonical entity always has the most columns (transforms only ever subset), so
  // prefer the column-count winner.
  const tablesByName = new Map<string, Table>();
  navigateProgram(program, {
    model: (m) => {
      const name = getTableName(program, m);
      if (!name) return;
      const candidate = collectTable(program, m, name);
      const existing = tablesByName.get(name);
      if (!existing) {
        tablesByName.set(name, candidate);
      } else {
        // Check for strict superset relationship
        const existingCols = new Set(existing.columns.map((c) => c.name));
        const candidateCols = new Set(candidate.columns.map((c) => c.name));
        const candidateIsSuperset = [...existingCols].every((c) => candidateCols.has(c)) && candidateCols.size > existingCols.size;
        const existingIsSuperset = [...candidateCols].every((c) => existingCols.has(c)) && existingCols.size > candidateCols.size;
        if (candidateIsSuperset) {
          tablesByName.set(name, candidate);
        } else if (!existingIsSuperset) {
          // Neither is a strict superset - conflict detected
          const existingColsStr = [...existingCols].sort().join(", ");
          const candidateColsStr = [...candidateCols].sort().join(", ");
          throw new Error(
            `Table name conflict for "${name}": Neither column set is a strict superset.\n` +
            `Existing columns: [${existingColsStr}]\n` +
            `Candidate columns: [${candidateColsStr}]`
          );
        }
      }
    },
  });
  const tables = [...tablesByName.values()];

  if (tables.length === 0) return;

  const ddlContent = renderDdlContent(tables);
  const version = hashVersion(ddlContent);
  await emitFile(program, {
    path: `${context.emitterOutputDir}/DuckDbSchema.g.cs`,
    content: renderClass(tables, version),
  });
}

function collectTable(program: Program, model: Model, name: string): Table {
  const columns: Column[] = [];
  for (const prop of model.properties.values()) {
    // Three-tier column-name resolution: explicit decorator > @encodedName("application/json") > camelCase→snake_case.
    // resolveEncodedName always returns prop.name when no @encodedName is set, so we compare to detect fallback.
    // Dot replacement is DuckDB-specific: @encodedName for OTel semconv keys like "deployment.id" lives in the
    // JSON wire format; DuckDB column names can't contain dots, so we fold to "deployment_id".
    const explicit = getColumnName(program, prop);
    const encoded = resolveEncodedName(program, prop as ModelProperty, "application/json");
    const rawName = explicit ?? (encoded !== prop.name ? encoded : camelToSnake(prop.name));
    const columnName = rawName.replace(/\./g, "_");
    const typeOverride =
      getColumnTypeOverride(program, prop)
      ?? (prop.type.kind === "Scalar" ? getColumnTypeOverride(program, prop.type as Scalar) : undefined);
    columns.push({
      name: columnName,
      type: typeOverride ?? mapType(program, prop.type),
      notNull: !prop.optional,
      primaryKey: isPrimaryKey(program, prop),
      indexes: getIndexes(program, prop),
    });
  }
  if (hasRowTimestamp(program, model) && !columns.some((c) => c.name === "created_at")) {
    columns.push({
      name: "created_at",
      type: "TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP",
      notNull: false,
      primaryKey: false,
      indexes: [],
    });
  }
  return { name, model, columns };
}

function camelToSnake(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/\./g, "_").toLowerCase();
}

function renderDdlContent(tables: Table[]): string {
  const out: string[] = [];
  for (const t of tables) {
    out.push(`CREATE TABLE IF NOT EXISTS ${t.name} (`);
    const lines: string[] = [];
    for (const c of t.columns) {
      let line = `    ${c.name} ${c.type}`;
      if (c.notNull && !c.type.toUpperCase().includes("DEFAULT")) line += " NOT NULL";
      lines.push(line);
      if (c.primaryKey) lines.push(`    PRIMARY KEY (${c.name})`);
    }
    out.push(lines.join(",\n"));
    out.push(");");
    for (const c of t.columns) for (const idx of c.indexes)
      out.push(`CREATE INDEX IF NOT EXISTS ${idx} ON ${t.name}(${c.name});`);
  }
  return out.join("\n") + "\n";
}

function renderClass(tables: Table[], version: number): string {
  const out: string[] = [HEADER, "namespace ANcpLua.OtelConventions.Collector.Storage;\n"];
  out.push("/// <summary>DuckDB schema generated from TypeSpec models.</summary>");
  out.push("public static partial class DuckDbSchema\n{");
  out.push(`    public const int Version = ${version};\n`);
  const constNames: string[] = [];
  const indexStmts: string[] = [];
  for (const t of tables) {
    const constName = `${pascalCase(t.name)}Ddl`;
    constNames.push(constName);
    out.push(`    public const string ${constName} = """`);
    out.push(`        CREATE TABLE IF NOT EXISTS ${t.name} (`);
    const colLines: string[] = [];
    for (const c of t.columns) {
      let line = `            ${c.name} ${c.type}`;
      if (c.notNull && !c.type.toUpperCase().includes("DEFAULT")) line += " NOT NULL";
      colLines.push(line);
      if (c.primaryKey) colLines.push(`            PRIMARY KEY (${c.name})`);
    }
    out.push(colLines.join(",\n"));
    out.push("        );");
    out.push('        """;\n');
    for (const c of t.columns) for (const idx of c.indexes)
      indexStmts.push(`        CREATE INDEX IF NOT EXISTS ${idx} ON ${t.name}(${c.name});`);
  }
  out.push("    public static string GetSchemaDdl() =>");
  out.push('        $"""');
  out.push(`        -- ANcpLua DuckDB Schema v${version}`);
  for (const n of constNames) out.push(`        {${n}}`);
  out.push(...indexStmts);
  out.push('        """;');
  out.push("}");
  return out.join("\n") + "\n";
}

function pascalCase(s: string): string {
  return s.split(/[_\s-]/).filter((x) => x.length > 0).map((x) => x[0].toUpperCase() + x.slice(1)).join("");
}

function hashVersion(ddl: string): number {
  return createHash("sha256").update(ddl, "utf8").digest().readUInt32BE(0) & 0x7fffffff;
}
