// Copyright (c) 2025-2026 ancplua
// SPDX-License-Identifier: MIT

import type { Program } from "@typespec/compiler";
import { reportDiagnostic, stateKeys, type QylAttrRecord } from "./index.js";
import { RESERVED_PREFIXES } from "./registry.js";

/**
 * Flatten the per-target state map buckets into a single array.
 */
function collectAll(program: Program): QylAttrRecord[] {
    const map = program.stateMap(stateKeys.qylAttr);
    const out: QylAttrRecord[] = [];
    for (const bucket of map.values()) {
        for (const rec of bucket as QylAttrRecord[]) out.push(rec);
    }
    return out;
}

/**
 * QYL-LINT-001 — attribute must live in the qyl registry namespace.
 *
 * The YAML attribute registry under eng/semconv/model/qyl/ is the source of
 * truth for qyl-owned telemetry keys (regenerated by Weaver into the three
 * runtime packages). Any `@qylAttr`-annotated key left inside the TypeSpec
 * pipeline must not collide with an upstream OTel namespace.
 */
function checkUpstreamCollision(program: Program, records: readonly QylAttrRecord[]): void {
    for (const r of records) {
        const collision = RESERVED_PREFIXES.find((p) => r.key.startsWith(p));
        if (collision) {
            reportDiagnostic(program, {
                code: "upstream-collision",
                target: r.target,
                format: { key: r.key, prefix: collision.slice(0, -1) },
            });
        }
    }
}

export function runAllRules(program: Program): void {
    const records = collectAll(program);
    if (records.length === 0) return;
    checkUpstreamCollision(program, records);
}
