import type { EmitContext, Enum, Model, Program } from "@typespec/compiler";
import { emitFile, navigateProgram } from "@typespec/compiler";
import { getCsharpNamespace, hasCsharpRecord } from "./decorators.js";
import { mapType } from "./type-map.js";

const HEADER = "﻿// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n#nullable enable\n";

type Bucket = { namespace: string; models: Array<[Model, string]>; enums: Enum[] };

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const buckets = new Map<string, Bucket>();
  const emittedNames = new Set<string>();

  navigateProgram(program, {
    model: (m) => {
      if (isInTypeSpec(m)) return;
      if (!m.name) return;
      const ns = resolveNamespace(program, m);
      if (!ns) return;
      // Template instantiations share the base name (`CursorPage`); use the instantiated
      // form `CursorPageTrace` so each instantiation produces a distinct type. Template
      // DEFINITIONS are not navigated, so this only fires on concrete instantiations.
      const emittedName = instantiationName(m);
      const key = `${ns}.${emittedName}`;
      if (emittedNames.has(key)) return;
      emittedNames.add(key);
      getBucket(buckets, ns).models.push([m, emittedName]);
    },
    enum: (e) => {
      if (isInTypeSpec(e)) return;
      const ns = resolveNamespace(program, e);
      if (!ns) return;
      getBucket(buckets, ns).enums.push(e);
    },
  });

  for (const [ns, bucket] of buckets) {
    const path = `${context.emitterOutputDir}/${ns.replace(/\./g, "/")}.cs`;
    await emitFile(program, { path, content: renderBucket(program, bucket) });
  }
}

function instantiationName(model: Model): string {
  if (!model.templateMapper?.args.length) return model.name;
  const parts = [model.name];
  for (const arg of model.templateMapper.args) {
    if ("kind" in arg && "name" in arg && typeof arg.name === "string") {
      parts.push(pascal(arg.name));
    }
  }
  return parts.join("");
}

function isInTypeSpec(type: { namespace?: { name?: string; namespace?: unknown } }): boolean {
  let cursor: { name?: string; namespace?: unknown } | undefined = type.namespace;
  while (cursor) {
    if (cursor.name === "TypeSpec") return true;
    cursor = cursor.namespace as typeof cursor;
  }
  return false;
}

function getBucket(buckets: Map<string, Bucket>, namespace: string): Bucket {
  let b = buckets.get(namespace);
  if (!b) {
    b = { namespace, models: [], enums: [] };
    buckets.set(namespace, b);
  }
  return b;
}

function resolveNamespace(program: Program, type: Model | Enum): string | undefined {
  const own = getCsharpNamespace(program, type);
  if (own) return own;
  let cursor = type.namespace;
  while (cursor) {
    const mapped = getCsharpNamespace(program, cursor);
    if (mapped) return mapped;
    cursor = cursor.namespace;
  }
  return undefined;
}

function renderBucket(program: Program, bucket: Bucket): string {
  const out: string[] = [HEADER];
  out.push(`namespace ${bucket.namespace};\n`);
  for (const [m, name] of bucket.models) out.push(renderModel(program, m, name));
  for (const e of bucket.enums) out.push(renderEnum(program, e));
  return out.join("\n");
}

function renderModel(program: Program, model: Model, emittedName: string): string {
  const asRecord = hasCsharpRecord(program, model);
  const keyword = asRecord ? "public sealed record" : "public sealed class";
  const props: string[] = [];
  for (const [, prop] of model.properties) {
    const type = mapType(program, prop.type);
    const name = pascal(prop.name);
    if (prop.optional) {
      props.push(`    public ${type}? ${name} { get; init; }`);
    } else {
      props.push(`    public required ${type} ${name} { get; init; }`);
    }
  }
  const body = props.length ? `\n${props.join("\n")}\n` : "\n";
  return `${keyword} ${emittedName}\n{${body}}\n`;
}

function renderEnum(_program: Program, enm: Enum): string {
  // Always emit as real C# enum. Static-const-string classes can't be used as property types
  // (CS0722), and modern System.Text.Json handles string↔enum with JsonStringEnumConverter.
  // Numeric member values are preserved; string member values are discarded — JSON emits the
  // C# member name via JsonStringEnumConverter. If string-value preservation is needed in a
  // specific case, @csharpEnum can still tune behavior, but the default is real enum.
  const members = [...enm.members.values()].map((m) => {
    const valueSuffix = typeof m.value === "number" ? ` = ${m.value}` : "";
    return `    ${pascal(m.name)}${valueSuffix}`;
  }).join(",\n");
  return `public enum ${enm.name}\n{\n${members}\n}\n`;
}

function pascal(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}
